IDE_HOME ?= /usr/local/arduino
SKETCHBOOK ?= $(HOME)/sketchbook
UPLOAD_PORT ?= /dev/ttyUSB0
PLATFORM_VERSION ?= 2.5.0

PROCESSOR_FAMILY := esp8266
PLATFORM := esp8266com
PLATFORM_PACKAGE := $(HOME)/.arduino15/packages/$(PROCESSOR_FAMILY)
PLATFORM_HEADER := Arduino.h
HARDWARE_FAMILY := $(PLATFORM_PACKAGE)/hardware/$(PROCESSOR_FAMILY)/$(PLATFORM_VERSION)
CORE := $(HARDWARE_FAMILY)/cores/$(PROCESSOR_FAMILY)
CPPFLAGS += -DARDUINO=10805
SKETCH_PRE = $(BUILD_DIR)/local.eagle.app.v6.common.ld

include ucmk.mk
include targets-esp8266.mk
