IDE_HOME ?= /usr/local/energia-0101E0017
SKETCHBOOK ?= $(HOME)/energia
PLATFORM := energia
PLATFORM_HEADER := Energia.h
CPPFLAGS += -DENERGIA=13 -DARDUINO=105

HARDWARE_FAMILY := $(IDE_HOME)/hardware/$(PROCESSOR_FAMILY)
CORE := $(HARDWARE_FAMILY)/cores/$(PROCESSOR_FAMILY)
TOOLS := $(IDE_HOME)/hardware/tools/$(PROCESSOR_FAMILY)

include ucmk.mk
